#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:C:\Users\pdw\Documents\GitHub\ESP2_0\MinSysEmbedProc\MinSysEmbedProc.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

SHELL = CMD

XILINX_EDK_DIR = C:/Xilinx/14.7/ISE_DS/EDK

SYSTEM = MinSysEmbedProc

MHSFILE = MinSysEmbedProc.mhs

FPGA_ARCH = spartan3a

DEVICE = xc3s1400anfgg676-5

INTSTYLE = ise

XPS_HDL_LANG = vhdl
GLOBAL_SEARCHPATHOPT = 
PROJECT_SEARCHPATHOPT = 

SEARCHPATHOPT = $(PROJECT_SEARCHPATHOPT) $(GLOBAL_SEARCHPATHOPT)

SUBMODULE_OPT =  -toplevel no -ti MinSysEmbedProc_i

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(XPS_HDL_LANG) -intstyle $(INTSTYLE) $(SEARCHPATHOPT) $(SUBMODULE_OPT) -msg __xps/ise/xmsgprops.lst

OBSERVE_PAR_OPTIONS = -error yes

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
MICROBLAZE_BOOTLOOP_LE = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop_le.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

MICROBLAZE_0_BOOTLOOP = $(BOOTLOOP_DIR)/microblaze_0.elf

BRAMINIT_ELF_IMP_FILES = $(MICROBLAZE_0_BOOTLOOP)
BRAMINIT_ELF_IMP_FILE_ARGS = -pe microblaze_0 $(MICROBLAZE_0_BOOTLOOP)

BRAMINIT_ELF_SIM_FILES = $(MICROBLAZE_0_BOOTLOOP)
BRAMINIT_ELF_SIM_FILE_ARGS = -pe microblaze_0 $(MICROBLAZE_0_BOOTLOOP)

SIM_CMD = isim_MinSysEmbedProc

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.tcl

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.tcl

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.tcl

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(XPS_HDL_LANG) -intstyle $(INTSTYLE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_SIM_FILE_ARGS) -msg __xps/ise/xmsgprops.lst -s isim -X C:/Users/pdw/Documents/GitHub/ESP2_0/MinSysEmbedProc/


CORE_STATE_DEVELOPMENT_FILES = pcores/rtephyseng_plbw_v1_00_c/netlist/xlpersistentdff.ngc \
pcores/rtephyseng_plbw_v1_00_c/netlist/mult_11_2_eb93f59d418f9076.ngc \
pcores/rtephyseng_plbw_v1_00_c/netlist/mult_11_2_22d5399536538cd3.ngc \
pcores/rtephyseng_plbw_v1_00_c/netlist/cntr_11_0_4c9ff32156a8ea89.ngc \
pcores/rtephyseng_plbw_v1_00_c/netlist/cntr_11_0_45469457c0a77b17.ngc \
pcores/rtephyseng_plbw_v1_00_c/netlist/cntr_11_0_42baf13c51a596fc.ngc \
pcores/rtephyseng_plbw_v1_00_c/netlist/bmg_72_24c7b3c86a194f2d.ngc \
pcores/rtephyseng_plbw_v1_00_c/netlist/block_memory_generator_spartan3a_7_3_db33641187955446.ngc \
pcores/rtephyseng_plbw_v1_00_c/netlist/block_memory_generator_spartan3a_7_3_d6efe1e2dc882263.ngc \
pcores/rtephyseng_plbw_v1_00_c/netlist/block_memory_generator_spartan3a_7_3_d28d1829125f404d.ngc \
pcores/rtephyseng_plbw_v1_00_c/netlist/block_memory_generator_spartan3a_7_3_c295182f8896cc0a.ngc \
pcores/rtephyseng_plbw_v1_00_c/netlist/block_memory_generator_spartan3a_7_3_9d1909bdf37ce107.ngc \
pcores/rtephyseng_plbw_v1_00_c/netlist/block_memory_generator_spartan3a_7_3_250f3887b741cf1f.ngc \
pcores/rtephyseng_plbw_v1_00_c/netlist/block_memory_generator_spartan3a_7_3_02f439fc3cb5ba3a.ngc \
pcores/rtephyseng_plbw_v1_00_c/netlist/addsb_11_0_50672071db3158cd.ngc \
pcores/rtephyseng_plbw_v1_00_c/hdl/vhdl/rtephyseng.vhd \
pcores/rtephyseng_plbw_v1_00_c/hdl/vhdl/block_memory_generator_spartan3a_7_3_d6efe1e2dc882263.vhd \
pcores/rtephyseng_plbw_v1_00_c/hdl/vhdl/block_memory_generator_spartan3a_7_3_250f3887b741cf1f.vhd \
pcores/rtephyseng_plbw_v1_00_c/hdl/vhdl/block_memory_generator_spartan3a_7_3_9d1909bdf37ce107.vhd \
pcores/rtephyseng_plbw_v1_00_c/hdl/vhdl/block_memory_generator_spartan3a_7_3_c295182f8896cc0a.vhd \
pcores/rtephyseng_plbw_v1_00_c/hdl/vhdl/rtephyseng_cw.vhd \
pcores/rtephyseng_plbw_v1_00_c/hdl/vhdl/rtephyseng_plbw.vhd

WRAPPER_NGC_FILES = implementation/MinSysEmbedProc_microblaze_0_wrapper.ngc \
implementation/MinSysEmbedProc_mb_plb_wrapper.ngc \
implementation/MinSysEmbedProc_ilmb_wrapper.ngc \
implementation/MinSysEmbedProc_dlmb_wrapper.ngc \
implementation/MinSysEmbedProc_dlmb_cntlr_wrapper.ngc \
implementation/MinSysEmbedProc_ilmb_cntlr_wrapper.ngc \
implementation/MinSysEmbedProc_lmb_bram_wrapper.ngc \
implementation/MinSysEmbedProc_clock_generator_0_wrapper.ngc \
implementation/MinSysEmbedProc_mdm_0_wrapper.ngc \
implementation/MinSysEmbedProc_proc_sys_reset_0_wrapper.ngc \
implementation/MinSysEmbedProc_xps_uartlite_0_wrapper.ngc \
implementation/MinSysEmbedProc_dtoa_converter_tl_0_wrapper.ngc \
implementation/MinSysEmbedProc_data_input_tl_0_wrapper.ngc \
implementation/MinSysEmbedProc_rtephyseng_plbw_0_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data\MinSysEmbedProc.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(XFLOW_DEPENDENCY)

SDK_EXPORT_DIR = SDK\SDK_Export\hw
SYSTEM_HW_HANDOFF = $(SDK_EXPORT_DIR)/$(SYSTEM).xml
SYSTEM_HW_HANDOFF_BIT = $(SDK_EXPORT_DIR)/$(SYSTEM).bit
SYSTEM_HW_HANDOFF_BMM = $(SDK_EXPORT_DIR)/$(SYSTEM)_bd.bmm
SYSTEM_HW_HANDOFF_DEP = $(SYSTEM_HW_HANDOFF)
